name: FOR SALE by Tracey
favicon: null
layout_spectrum: 0.4371291378047317
typography_spectrum: 0.7316020149737597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6103089256212115
  lightness: 0.321617215173319
  saturation: 0.9405142057221383
  rhythmicContrast: 0.9554606075398624
purpose: []
