name: FOR SALE by Tracey
favicon: null
layout_spectrum: 0.95746
typography_spectrum: 0.28896
title: "Live Local Listings! SEMO's up-to-the-minute real estate listings & local biz reviews!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6aa400'
    - '#000000'
    - '#ffde00'
    - '#b70e00'
    - '#ffffff'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
